apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetstream-frontend
  namespace: tweetstream
  labels:
    app.kubernetes.io/name: tweetstream
    app.kubernetes.io/instance: tweetstream
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: tweetstream
      app.kubernetes.io/instance: tweetstream
      component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tweetstream
        app.kubernetes.io/instance: tweetstream
        component: frontend
    spec:
      containers:
      - name: frontend
        image: 192.168.1.82:5555/tweetstream/frontend:2.2.0
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tweetstream-frontend
  namespace: tweetstream
  labels:
    app.kubernetes.io/name: tweetstream
    app.kubernetes.io/instance: tweetstream
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: tweetstream
    app.kubernetes.io/instance: tweetstream
    component: frontend 