{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tweetstream.fullname" . }}-api
  namespace: {{ include "tweetstream.namespace" . }}
  labels:
    {{- include "tweetstream.labels" . | nindent 4 }}
    component: monitoring
spec:
  selector:
    matchLabels:
      {{- include "tweetstream.selectorLabels" . | nindent 6 }}
      component: api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
{{- end }} 