apiVersion: v2
name: tweetstream
description: A production-ready Twitter-like social media platform for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/tweetstream
sources:
  - https://github.com/your-org/tweetstream
maintainers:
  - name: TweetStream Team
    email: team@tweetstream.io
keywords:
  - social-media
  - twitter
  - microservices
  - kafka
  - postgresql
  - redis
  - nodejs
annotations:
  category: Application
  licenses: MIT
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "22.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled 