# TweetStream Development Environment Values
# Minimal resources for local development

# Global settings
global:
  environment: development
  imageRegistry: ""
  storageClass: "local-path"

# API Service - Minimal for dev
api:
  enabled: true
  replicaCount: 1
  
  autoscaling:
    enabled: false
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Frontend - Minimal for dev
frontend:
  enabled: true
  replicaCount: 1
  
  autoscaling:
    enabled: false
  
  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"
    limits:
      memory: "64Mi"
      cpu: "50m"

# Database - Smaller for dev
database:
  enabled: true
  
  persistence:
    size: "2Gi"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "100m"

# Redis - Smaller for dev
redis:
  enabled: true
  
  persistence:
    size: "500Mi"
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "50m"

# Kafka - Smaller for dev
kafka:
  enabled: true
  
  persistence:
    size: "1Gi"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

# Monitoring - Disabled for dev
monitoring:
  enabled: false

# Ingress
ingress:
  enabled: true
  hosts:
    - host: tweetstream-dev.192.168.1.82.nip.io
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: api 