# TweetStream Staging Environment Values
# Moderate resources for testing and staging

# Global settings
global:
  environment: staging
  imageRegistry: ""
  storageClass: "local-path"

# API Service - Moderate for staging
api:
  enabled: true
  replicaCount: 2
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Frontend - Moderate for staging
frontend:
  enabled: true
  replicaCount: 2
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Database - Standard for staging
database:
  enabled: true
  
  persistence:
    size: "5Gi"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "200m"

# Redis - Standard for staging
redis:
  enabled: true
  
  persistence:
    size: "1Gi"
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Kafka - Standard for staging
kafka:
  enabled: true
  
  persistence:
    size: "3Gi"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Monitoring - Enabled for staging
monitoring:
  enabled: true
  
  serviceMonitor:
    enabled: true
    interval: 30s
  
  grafanaDashboard:
    enabled: true
  
  prometheusRules:
    enabled: true

# Ingress
ingress:
  enabled: true
  hosts:
    - host: tweetstream-staging.192.168.1.82.nip.io
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: api 